### ISSUE TITLE
Client error for STOW-RS

### ISSUE THREAD

**Issue by jinserk** [clindatsci/dicomweb-client#7]
I lefted another question for the `store_instances()` but it's already closed and won't get any further notice to you, so please excuse me to make another new thread.  I'm almost newbie to deal with the dicom standard, but the following example code has an error:
```
import os
import tempfile
import datetime

import pydicom
from pydicom.dataset import Dataset, FileDataset
from pydicom.sequence import Sequence

# Create some temporary filenames
suffix = '.dcm'
filename_little_endian = tempfile.NamedTemporaryFile(suffix=suffix).name
filename_big_endian = tempfile.NamedTemporaryFile(suffix=suffix).name

print("Setting file meta information...")
# Populate required values for file meta information
file_meta = Dataset()
file_meta.MediaStorageSOPClassUID = '1.2.840.10008.5.1.4.1.1.2'
file_meta.MediaStorageSOPInstanceUID = "1.2.3"
file_meta.ImplementationClassUID = "1.2.3.4"

print("Setting dataset values...")
# Create the FileDataset instance (initially no data elements, but file_meta
# supplied)
ds = FileDataset(filename_little_endian, {},
                 file_meta=file_meta, preamble=b"\0" * 128)

# Add the data elements -- not trying to set all required here. Check DICOM
# standard
ds.PatientName = "Test^Firstname"
ds.PatientID = "123456"

# Set the transfer syntax
ds.is_little_endian = True
ds.is_implicit_VR = True

# Set creation date/time
dt = datetime.datetime.now()
ds.ContentDate = dt.strftime('%Y%m%d')
timeStr = dt.strftime('%H%M%S.%f')  # long format with micro seconds
ds.ContentTime = timeStr

print("Writing test file", filename_little_endian)
ds.save_as(filename_little_endian)
print("File saved.")


from dicomweb_client.api import DICOMwebClient

client = DICOMwebClient("http://172.19.2.123:8042/dicom-web")
STUDY_UID = '2.16.840.1.114488.0.4.123489834087.1330071425.0'
client.store_instances(datasets=[ds])
```
and the error message is:
```
Setting file meta information...
Setting dataset values...
Writing test file /tmp/tmph64u7s3j.dcm
File saved.
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    client.store_instances(datasets=[ds])
  File "/home/jinserk/.pyenv/versions/3.7.2/lib/python3.7/site-packages/dicomweb_client/api.py", line 1797, in store_instances
    self._http_post_multipart_application_dicom(url, encoded_datasets)
  File "/home/jinserk/.pyenv/versions/3.7.2/lib/python3.7/site-packages/dicomweb_client/api.py", line 1207, in _http_post_multipart_application_dicom
    self._http_post(url, content, headers={'Content-Type': content_type})
  File "/home/jinserk/.pyenv/versions/3.7.2/lib/python3.7/site-packages/dicomweb_client/api.py", line 1186, in _http_post
    response.raise_for_status()
  File "/home/jinserk/.pyenv/versions/3.7.2/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://172.19.2.123:8042/dicom-web/studies
```

Here what I wonder that:
- why the request added "studies"?
- how can I give 'study uid' to store_instances function? do I need to add the info into the dataset?
- how to add another series to existing study?

**Comment by hackermd** [comment]
Please refer to [DICOM PS3.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.3.html) on how to create a DICOM dataset.

> why the request added "studies"

Please refer to [DICOM PS3.18](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_6.6.html).

> how can I give 'study uid' to store_instances function

Please refer to the API documentation of `store_instances()`: https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMwebClient.store_instances

**Comment by jinserk** [comment]
Thank you so much for the response, @hackermd! 

Can I ask you one thing more? If I want to replace an existing instance, is there any way to this using dicomweb-client? I have tried to retrieve an instace and added some private tags to it, then `store_instances()` is completed quietly, but nothing has changed on the server.

**Comment by hackermd** [comment]
Check the status code of the response message by increasing the logging level.

DICOM instances are immutable, so you can't "replace" an existing instance.
